In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("extracted.csv")

In [10]:
df.columns
df.dtypes

file               object
url                object
texts              object
price              object
images             object
article_number    float64
datasheets         object
variants           object
dtype: object

In [13]:
df

,file,url,texts,price,images,article_number,datasheets,variants
0,page_0.html,https://www.geneon.net/,Edit here your header slider GeneON-BioScience...,NaN,"[""https://u.jimcdn.com/e/o/s992ea961e2602c7c/u...",NaN,[],[]
1,page_1.html,https://www.geneon.net/english-pages/ablage/,Expression of actin gene with Universal Flex q...,NaN,"[""https://image.jimcdn.com/app/cms/image/trans...",NaN,[],[]
2,page_10.html,https://www.geneon.net/products/dna-rna-extrac...,Blood DNA Purification Kit - extraction of DNA...,"85,00 €","[""https://image.jimcdn.com/app/cms/image/trans...",1.427545e+10,"[""https://www.geneon.net/app/download/18410301...","[[""BD50 - 50 preps 85,00 €"", ""BD100 - 100 prep..."
3,page_100.html,https://www.geneon.net/products/biochemicals-a...,"Buffer for Electrophoresis, Western Blotting, ...","259,00 €","[""https://image.jimcdn.com/app/cms/image/trans...",1.710563e+10,[],[]
4,page_101.html,https://www.geneon.net/agarose/,Agarose for perfect results in gel electrophor...,"179,00 €","[""https://image.jimcdn.com/app/cms/image/trans...",1.522236e+10,"[""https://www.geneon.net/app/download/15629792...","[[""604-005 - 500 gr - Agarose - 179,00 €"", ""60..."
...,...,...,...,...,...,...,...,...
438,page_95.html,https://www.geneon.net/reverse-transcriptase/r...,RNase Inhibitor - RNA protector - RNasin. Avai...,"139,00 €","[""https://image.jimcdn.com/app/cms/image/trans...",1.510945e+10,"[""https://www.geneon.net/app/download/18138666...","[[""105-350 - 10.000 Units - SPECIAL PRICE 139,..."
439,page_96.html,https://www.geneon.net/products/rt-pcr-reverse...,Random Primers Mixture of single-stranded rand...,"28,00 €","[""https://image.jimcdn.com/app/cms/image/trans...",1.510953e+10,"[""https://www.geneon.net/app/download/14409566...",[]
440,page_97.html,https://www.geneon.net/products/rt-pcr-reverse...,RT-PCR Reverse Transcription: Datasheet collec...,NaN,[],NaN,"[""https://www.geneon.net/app/download/15229236...",[]
441,page_98.html,https://www.geneon.net/products/biochemicals-a...,"Agarose, Proteinase K, DNase, RNase A, Lyophil...",NaN,"[""https://image.jimcdn.com/app/cms/image/trans...",NaN,[],[]
442,page_99.html,https://www.geneon.net/products/enzymes-and-fi...,Collection of Datasheets: Finechemicals RNaseI...,NaN,[],NaN,"[""https://www.geneon.net/app/download/15222422...",[]

In [ ]:
import ast

df = pd.read_csv("extracted.csv")

# remove pages without price (non-product pages)
df = df[df["price"].notna()]

# convert article number
df["article_number"] = df["article_number"].astype(str)

# convert lists stored as text
df["images"] = df["images"].apply(ast.literal_eval)
df["datasheets"] = df["datasheets"].apply(ast.literal_eval)
df["variants"] = df["variants"].apply(ast.literal_eval)

df.to_csv("clean_geneon_products.csv", index=False)

print("Clean products:", len(df))

Clean products: 370

In [15]:
df

,file,url,texts,price,images,article_number,datasheets,variants
2,page_10.html,https://www.geneon.net/products/dna-rna-extrac...,Blood DNA Purification Kit - extraction of DNA...,"85,00 €",[https://image.jimcdn.com/app/cms/image/transf...,14275448096.0,[https://www.geneon.net/app/download/184103013...,"[[BD50 - 50 preps 85,00 €, BD100 - 100 preps 1..."
3,page_100.html,https://www.geneon.net/products/biochemicals-a...,"Buffer for Electrophoresis, Western Blotting, ...","259,00 €",[https://image.jimcdn.com/app/cms/image/transf...,17105627996.0,[],[]
4,page_101.html,https://www.geneon.net/agarose/,Agarose for perfect results in gel electrophor...,"179,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15222360796.0,[https://www.geneon.net/app/download/156297922...,"[[604-005 - 500 gr - Agarose - 179,00 €, 604-0..."
5,page_102.html,https://www.geneon.net/products/enzymes-and-fi...,Low Melt Agarose (PRODUCT IS DISCONTINUED) Low...,"0,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15222356696.0,[https://www.geneon.net/app/download/152290976...,[]
6,page_103.html,https://www.geneon.net/bsa-bovine-serum-albumin/,Bovine Serum Albumin - BSA nativ - non-acetyla...,"38,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15222353296.0,[https://www.geneon.net/app/download/152290920...,"[[209-005 (Glycerol NEB-Buffer) - 4x1,5 ml - 3..."
...,...,...,...,...,...,...,...,...
435,page_92.html,https://www.geneon.net/reverse-transcription/m...,M-MuLV Reverse Transcriptase M-MuLV-Reverse Tr...,"229,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15109423896.0,[https://www.geneon.net/app/download/164805513...,"[[105-250- 50.000 Units - 229,00 €, 105-100 - ..."
436,page_93.html,https://www.geneon.net/products/rt-pcr-reverse...,AMV Reverse Transcriptase AMV Reverse Transcri...,"0,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15109570196.0,[https://www.geneon.net/app/download/152292365...,[]
437,page_94.html,https://www.geneon.net/products/rt-pcr-reverse...,Oligo (dT)15 Standard primer for RT-PCR Descri...,"31,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15109512996.0,[https://www.geneon.net/app/download/152292393...,[]
438,page_95.html,https://www.geneon.net/reverse-transcriptase/r...,RNase Inhibitor - RNA protector - RNasin. Avai...,"139,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15109450596.0,[https://www.geneon.net/app/download/181386660...,"[[105-350 - 10.000 Units - SPECIAL PRICE 139,0..."
439,page_96.html,https://www.geneon.net/products/rt-pcr-reverse...,Random Primers Mixture of single-stranded rand...,"28,00 €",[https://image.jimcdn.com/app/cms/image/transf...,15109531996.0,[https://www.geneon.net/app/download/144095663...,[]

In [ ]:
import ast

df = pd.read_csv("extracted.csv")

# remove pages without price
df = df[df["price"].notna()]

# fix article numbers
df["article_number"] = df["article_number"].astype(str)

def safe_eval(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

df["images"] = df["images"].apply(safe_eval)
df["datasheets"] = df["datasheets"].apply(safe_eval)
df["variants"] = df["variants"].apply(safe_eval)

df.to_csv("Clean_geneon_products.csv", index=False)

print("Clean products:", len(df))

Clean products: 370

In [ ]:
df = pd.read_csv("clean_geneon_products.csv")

# fix article numbers
df["article_number"] = df["article_number"].apply(lambda x: str(int(float(x))) if pd.notna(x) else "")
df = df[df["variants"].astype(str) != "[]"]
df.to_csv("clean_geneon_products_FIXED.csv", index=False)

print("Done")

Done

In [5]:

df = pd.read_csv("extracted.csv")

# remove pages without price
df = df[df["price"].notna()]

# fix article numbers
df["article_number"] = df["article_number"].astype(str)

def safe_eval(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

df["images"] = df["images"].apply(safe_eval)
df["datasheets"] = df["datasheets"].apply(safe_eval)
df["variants"] = df["variants"].apply(safe_eval)

df.to_csv("Clean_geneon_products.csv", index=False)

print("Clean products:", len(df))

Clean products: 370

In [7]:
df = df[df["images"].notna()]

In [8]:
df

,file,url,texts,price,images,article_number,datasheets,variants
2,page_10.html,https://www.geneon.net/products/dna-rna-extrac...,Blood DNA Purification Kit - extraction of DNA...,"85,00 €",[],14275448096.0,[],[]
3,page_100.html,https://www.geneon.net/products/biochemicals-a...,"Buffer for Electrophoresis, Western Blotting, ...","259,00 €",[],17105627996.0,[],[]
4,page_101.html,https://www.geneon.net/agarose/,Agarose for perfect results in gel electrophor...,"179,00 €",[],15222360796.0,[],[]
5,page_102.html,https://www.geneon.net/products/enzymes-and-fi...,Low Melt Agarose (PRODUCT IS DISCONTINUED) Low...,"0,00 €",[],15222356696.0,[],[]
6,page_103.html,https://www.geneon.net/bsa-bovine-serum-albumin/,Bovine Serum Albumin - BSA nativ - non-acetyla...,"38,00 €",[],15222353296.0,[],[]
...,...,...,...,...,...,...,...,...
435,page_92.html,https://www.geneon.net/reverse-transcription/m...,M-MuLV Reverse Transcriptase M-MuLV-Reverse Tr...,"229,00 €",[],15109423896.0,[],[]
436,page_93.html,https://www.geneon.net/products/rt-pcr-reverse...,AMV Reverse Transcriptase AMV Reverse Transcri...,"0,00 €",[],15109570196.0,[],[]
437,page_94.html,https://www.geneon.net/products/rt-pcr-reverse...,Oligo (dT)15 Standard primer for RT-PCR Descri...,"31,00 €",[],15109512996.0,[],[]
438,page_95.html,https://www.geneon.net/reverse-transcriptase/r...,RNase Inhibitor - RNA protector - RNasin. Avai...,"139,00 €",[],15109450596.0,[],[]
439,page_96.html,https://www.geneon.net/products/rt-pcr-reverse...,Random Primers Mixture of single-stranded rand...,"28,00 €",[],15109531996.0,[],[]

In [ ]:
import ast

# Load CSV
df = pd.read_csv("extracted.csv")

# 1. Remove spaces 
for col in df.columns:
    df[col] = df[col].map(lambda x: x.strip() if isinstance(x, str) else x)

# 2. Convert list-like text
list_columns = ["images", "datasheets", "variants"]

for col in list_columns:
    df[col] = df[col].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith("[") else x
    )

# 3. Clean text column
df["texts"] = df["texts"].astype(str).str.replace("\n", " ")

# 4. Convert lists to string
# (for duplicate checking)
for col in list_columns:
    df[col] = df[col].astype(str)

# 5. Remove duplicates
df = df.drop_duplicates()

# 6. Reset index
df = df.reset_index(drop=True)

# 7. Save clean dataset
df.to_csv("test1.csv", index=False)

print("✅ Clean dataset saved")

✅ Clean dataset saved

In [3]:
df = df[
    df["images"].notna() &
    df["datasheets"].notna() &
    (df["images"] != "[]") &
    (df["datasheets"] != "[]")
]

In [ ]:

df.to_csv("CLEANED_DATA", index=False)

In [6]:
import ast

df["images"] = df["images"].apply(
    lambda x: ast.literal_eval(x)[0] if isinstance(x, str) and x.startswith("[") else x
)

In [ ]:
import ast

for col in ["images", "datasheets"]:
    df[col] = df[col].apply(
        lambda x: ast.literal_eval(x)[0] if isinstance(x, str) and x.startswith("[") else x
    )

df.to_csv("test4.csv", index=False)